variables:
  GIT_STRATEGY: clone

stages:
  - release

#################################################################
# release stage jobs
#################################################################

semantic_release:
  stage: release
  image: node:12-buster
  only:
    refs:
      - master
  before_script:
    - update-alternatives --install /usr/bin/python python /usr/bin/python3 1
    - curl -sSL  https://bootstrap.pypa.io/get-pip.py | python
    - pip install adr-viewer
    - npm install -g semantic-release@"^17.0.4"
    - npm install -g @semantic-release/changelog@"^5.0.0"
    - npm install -g @semantic-release/exec@"^5.0.0"
    - npm install -g @semantic-release/git@"^9.0.0"
#    - npm install -g @semantic-release/gitlab@"^6.0.2"
  script:
    - npx semantic-release
